# Make Tables

buffer <- 30
planned_cutoff_year <- 2010

models <- readRDS(file.path(results_file_path, "models_30km.Rds"))

#models$china_influential_index_30_full %>% summary()

splag <- "T"
splag <- "F"

# ROUND 6 MODELS ===============================================================

# Table 1 - 2010: Full ----------------------------------------------------------------
stargazer(influential_index.full.lm,
          positive_influence_index.full.lm,
          china.most.influence.full.lm,
          usa.most.influence.full.lm,
          china.best.dev.model.full.lm,
          usa.best.dev.model.full.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(influential_index.full.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.full.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.full.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.full.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.full.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.full.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model.full.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full.tex"))

# Table 1 - 2010: Restricted ----------------------------------------------------------
stargazer(influential_index.restricted.lm,
          positive_influence_index.restricted.lm,
          china.most.influence.restricted.lm,
          usa.most.influence.restricted.lm,
          china.best.dev.model.restricted.lm,
          usa.best.dev.model.restricted.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(influential_index.restricted.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.restricted.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.restricted.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.restricted.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.restricted.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.restricted.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(influential_index.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model.restricted.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted.tex"))

# Table 1 - 2009: Full ---------------------------------------------------------
stargazer(influential_index.full.lm,
          positive_influence_index.full.lm,
          china.most.influence.full.lm,
          usa.most.influence.full.lm,
          china.best.dev.model.full.lm,
          usa.best.dev.model.full.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(influential_index.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model.full.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full_2008.tex"))

# Table 1 - 2009: Restricted ---------------------------------------------------------
stargazer(influential_index.restricted.lm,
          positive_influence_index.restricted.lm,
          china.most.influence.restricted.lm,
          usa.most.influence.restricted.lm,
          china.best.dev.model.restricted.lm,
          usa.best.dev.model.restricted.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(influential_index.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(influential_index.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model.restricted.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted_2008.tex"))

# Table 1 - 2008: Full ---------------------------------------------------------
stargazer(influential_index.full.lm,
          positive_influence_index.full.lm,
          china.most.influence.full.lm,
          usa.most.influence.full.lm,
          china.best.dev.model.full.lm,
          usa.best.dev.model.full.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(influential_index.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.full.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model.full.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full_2008.tex"))

# Table 1 - 2008: Restricted ---------------------------------------------------------
stargazer(influential_index.restricted.lm,
          positive_influence_index.restricted.lm,
          china.most.influence.restricted.lm,
          usa.most.influence.restricted.lm,
          china.best.dev.model.restricted.lm,
          usa.best.dev.model.restricted.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(influential_index.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.restricted.lm, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(influential_index.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model.restricted.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted_2008.tex"))


# Table 3 - Full -------------------------------------------------------------------
stargazer(formcolnpower.most.influence.full.lm,
          formcolnpower.best.dev.model.full.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Former Colonial Power", "Former Colonial Power"),
          column.labels   = c("Most Influential", "Best Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(formcolnpower.most.influence.full.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(formcolnpower.best.dev.model.full.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(formcolnpower.most.influence.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(formcolnpower.best.dev.model.full.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "table_03_full.tex"))

# Table 3 - Restricted -------------------------------------------------------------
stargazer(formcolnpower.most.influence.restricted.lm,
          formcolnpower.best.dev.model.restricted.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Former Colonial Power", "Former Colonial Power"),
          column.labels   = c("Most Influential", "Best Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(formcolnpower.most.influence.restricted.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(formcolnpower.best.dev.model.restricted.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(formcolnpower.most.influence.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(formcolnpower.best.dev.model.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(formcolnpower.most.influence.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(formcolnpower.best.dev.model.restricted.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "table_03_restricted.tex"))

# Table 5 ----------------------------------------------------------------------
stargazer(posimage_chinesepeople.lm,
          posimage_businessinvetment.lm,
          posimage_infordevinvetment.lm,
          posimage_noninterference.lm,
          posimage_supportinintlaffiars.lm,
          posimage_productcost.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Chinese People ","Business","Inf / Development","Non-Interference","Support in","Cost of"),
          column.labels   = c("and Culture", "Investment", "Investment",      "Policy",           "Intl Affairs", "Chinese Products"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(posimage_chinesepeople.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_businessinvetment.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_infordevinvetment.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_noninterference.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_supportinintlaffiars.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_productcost.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(posimage_chinesepeople.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_businessinvetment.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_infordevinvetment.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_noninterference.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_supportinintlaffiars.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_productcost.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y","Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_05_full.tex"))

# Table 6 ----------------------------------------------------------------------
stargazer(negimage_cooperateundemocratic.lm,
          negimage_chinesecitizenbehavior.lm,
          negimage_resourceextraction.lm,
          negimage_takingjobsbusiness.lm,
          negimage_landgrabbing.lm,
          negimage_productquality.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Coop With",     "Behavior of ",    "Resource",   "Taking Jobs",   "Land",     "Product"),
          column.labels   = c("Undem Leaders", "Chinese Citzns", "Extraction", "and Business",  "Grabbing", "Quality"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(negimage_cooperateundemocratic.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_chinesecitizenbehavior.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_resourceextraction.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_takingjobsbusiness.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_landgrabbing.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_productquality.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(negimage_cooperateundemocratic.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_chinesecitizenbehavior.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_resourceextraction.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_takingjobsbusiness.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_landgrabbing.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_productquality.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y","Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_06_full.tex"))

# Table 7 ----------------------------------------------------------------------
stargazer(china_dontknow_index.lm,
          china.influence.econ.activity_DONTKNOW.lm,
          china.econpol.influence.positive_DONTKNOW.lm,
          china.aid.good.job.meet.country.needs_DONTKNOW.lm,
          china.help.country_DONTKNOW.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Chinese Q Don't", "Chinese Econ Activity",  "Econ/Pol Influ.",   "Chinese Aid Meets",     "China Helps"),
          column.labels   = c("Know [Index]",   "Influ. Economy [DK]",    "Pos. or Neg. [DK]", "Country's Needs [DK]",  "Country [DK]"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(china_dontknow_index.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.influence.econ.activity_DONTKNOW.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.econpol.influence.positive_DONTKNOW.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.aid.good.job.meet.country.needs_DONTKNOW.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.help.country_DONTKNOW.lm, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(china_dontknow_index.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.influence.econ.activity_DONTKNOW.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.econpol.influence.positive_DONTKNOW.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.aid.good.job.meet.country.needs_DONTKNOW.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.help.country_DONTKNOW.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer)),
          out=file.path(tables_file_path, "table_07_full.tex"))

# ROUND 4 MODELS ===============================================================

# Table x ----------------------------------------------------------------------
stargazer(china.help.country.lm,
          usa.help.country.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Believes","Believes"),
          column.labels   = c("China Helps", "US Helps"),
          keep=c("completed_near_china.plNA.30km.bin",   "planned_near_china.plNA.30km.bin"),
          covariate.labels = c("China Completed", "China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned infrastructure $p$-value", 
              tryCatch(round(linearHypothesis(china.help.country.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.help.country.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(china.help.country.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.help.country.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "round4_table.tex"))

# Table x - Planned Eventually Completed ---------------------------------------
stargazer(china.help.country.lm,
          usa.help.country.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Believes","Believes"),
          column.labels   = c("China Helps", "US Helps"),
          keep=c("completed_near_china.plNAcmpltd.30km.bin",   "planned_near_china.plNAcmpltd.30km.bin"),
          covariate.labels = c("China Completed", "China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned infrastructure $p$-value", 
              tryCatch(round(linearHypothesis(china.help.country.lm, "completed_near_china.plNAcmpltd.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.help.country.lm, "completed_near_china.plNAcmpltd.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(china.help.country.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.help.country.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "round4_table_plannedCompleted.tex"))

# ROUND 2-5 MODELS =============================================================

# Table 2 - Full ---------------------------------------------------------------
stargazer(lib_dem_val_index.full.lm,
          blvs_mult_parties_good.full.lm,
          blvs_mult_parties_create_choice.full.lm,
          blvs_ctzn_should_join_any_cso.full.lm,
          blvs_democ_best_system.full.lm,
          blvs_elec_good.full.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNA.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(lib_dem_val_index.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good.full.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer, buffer)),
          out=file.path(tables_file_path, "table_02_full.tex"))

# Table 2 - Restricted ---------------------------------------------------------
stargazer(lib_dem_val_index.restricted.lm,
          blvs_mult_parties_good.restricted.lm,
          blvs_mult_parties_create_choice.restricted.lm,
          blvs_ctzn_should_join_any_cso.restricted.lm,
          blvs_democ_best_system.restricted.lm,
          blvs_elec_good.restricted.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNA.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good.restricted.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_02_restricted.tex"))

# Table 2 - Planned Eventually Completed: Full ---------------------------------
stargazer(lib_dem_val_index.full.lm,
          blvs_mult_parties_good.full.lm,
          blvs_mult_parties_create_choice.full.lm,
          blvs_ctzn_should_join_any_cso.full.lm,
          blvs_democ_best_system.full.lm,
          blvs_elec_good.full.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNAcmpltd.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(lib_dem_val_index.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good.full.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system.full.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good.full.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer, buffer)),
          out=file.path(tables_file_path, "table_02_plannedCompleted_full.tex"))

# Table 2 - Planned Eventually Completed: Restricted ---------------------------
stargazer(lib_dem_val_index.restricted.lm,
          blvs_mult_parties_good.restricted.lm,
          blvs_mult_parties_create_choice.restricted.lm,
          blvs_ctzn_should_join_any_cso.restricted.lm,
          blvs_democ_best_system.restricted.lm,
          blvs_elec_good.restricted.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNAcmpltd.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good.restricted.lm, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good.restricted.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_02_plannedCompleted_restricted.tex"))

# Table 4 ----------------------------------------------------------------------
stargazer(lib_dem_val_index.lm,
          blvs_mult_parties_good.restricted.lm,
          blvs_mult_parties_create_choice.restricted.lm,
          blvs_ctzn_should_join_any_cso.restricted.lm,
          blvs_democ_best_system.restricted.lm,
          blvs_elec_good.restricted.lm,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin",
                 "completed_near_ukaid.30km.bin", "planned_near_ukaid.30km.bin"),
          covariate.labels = c("USA Completed","USA Planned",
                               "UK Completed","UK Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good.restricted.lm, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [UK]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index.lm, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good.restricted.lm, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice.restricted.lm, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso.restricted.lm, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system.restricted.lm, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good.restricted.lm, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system.restricted.lm)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good.restricted.lm)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer)),
          out=file.path(tables_file_path, "table_04_restricted.tex"))














