# Make Tables

buffer <- 30
planned_cutoff_year <- 2010
splag <- "T"
splag <- "F"

df <- readRDS(file.path(data_file_path, "afro_china_data.Rds"))

# Load all models
for(model_path in list.files(results_file_path)){
  model_name <- model_path %>% str_replace_all(".Rds", "")
  model <- readRDS(file.path(results_file_path, model_path))
  
  print(model_name)
  assign(model_name, model)
  rm(model_name, model)
}


# ROUND 6 MODELS ===============================================================

# Table 1 - 2010: Full ----------------------------------------------------------------
stargazer(influential_index_full,
          positive_influence_index_full,
          china.most.influence_full,
          usa.most.influence_full,
          china.best.dev.model_full,
          usa.best.dev.model_full,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(influential_index_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full.tex"))

# Table 1 - 2010: Restricted ----------------------------------------------------------
stargazer(influential_index_restricted,
          positive_influence_index_restricted,
          china.most.influence_restricted,
          usa.most.influence_restricted,
          china.best.dev.model_restricted,
          usa.best.dev.model_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(influential_index_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(influential_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted.tex"))

# Table 1 - 2009: Full ---------------------------------------------------------
stargazer(influential_index_full,
          positive_influence_index_full,
          china.most.influence_full,
          usa.most.influence_full,
          china.best.dev.model_full,
          usa.best.dev.model_full,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(influential_index_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full_2008.tex"))

# Table 1 - 2009: Restricted ---------------------------------------------------------
stargazer(influential_index_restricted,
          positive_influence_index_restricted,
          china.most.influence_restricted,
          usa.most.influence_restricted,
          china.best.dev.model_restricted,
          usa.best.dev.model_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(influential_index_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(influential_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted_2008.tex"))

# Table 1 - 2008: Full ---------------------------------------------------------
stargazer(influential_index_full,
          positive_influence_index_full,
          china.most.influence_full,
          usa.most.influence_full,
          china.best.dev.model_full,
          usa.best.dev.model_full,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(influential_index_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full_2008.tex"))

# Table 1 - 2008: Restricted ---------------------------------------------------------
stargazer(influential_index_restricted,
          positive_influence_index_restricted,
          china.most.influence_restricted,
          usa.most.influence_restricted,
          china.best.dev.model_restricted,
          usa.best.dev.model_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(influential_index_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(influential_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(positive_influence_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(influential_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(positive_influence_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.best.dev.model_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.best.dev.model_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted_2008.tex"))


# Table 3 - Full -------------------------------------------------------------------
stargazer(formcolnpower.most.influence_full,
          formcolnpower.best.dev.model_full,
          dep.var.labels.include = T,
          dep.var.labels = c("Former Colonial Power", "Former Colonial Power"),
          column.labels   = c("Most Influential", "Best Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(formcolnpower.most.influence_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(formcolnpower.best.dev.model_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(formcolnpower.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(formcolnpower.best.dev.model_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "table_03_full.tex"))

# Table 3 - Restricted -------------------------------------------------------------
stargazer(formcolnpower.most.influence_restricted,
          formcolnpower.best.dev.model_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("Former Colonial Power", "Former Colonial Power"),
          column.labels   = c("Most Influential", "Best Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(formcolnpower.most.influence_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(formcolnpower.best.dev.model_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(formcolnpower.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(formcolnpower.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(formcolnpower.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(formcolnpower.best.dev.model_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "table_03_restricted.tex"))

# Table 5 ----------------------------------------------------------------------
stargazer(posimage_chinesepeople,
          posimage_businessinvetment,
          posimage_infordevinvetment,
          posimage_noninterference,
          posimage_supportinintlaffiars,
          posimage_productcost,
          dep.var.labels.include = T,
          dep.var.labels = c("Chinese People ","Business","Inf / Development","Non-Interference","Support in","Cost of"),
          column.labels   = c("and Culture", "Investment", "Investment",      "Policy",           "Intl Affairs", "Chinese Products"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(posimage_chinesepeople, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_businessinvetment, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_infordevinvetment, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_noninterference, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_supportinintlaffiars, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(posimage_productcost, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(posimage_chinesepeople)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_businessinvetment)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_infordevinvetment)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_noninterference)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_supportinintlaffiars)$p.value %>% round(ROUND_NUM),
              calc_morans_i(posimage_productcost)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y","Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_05_full.tex"))

# Table 6 ----------------------------------------------------------------------
stargazer(negimage_cooperateundemocratic,
          negimage_chinesecitizenbehavior,
          negimage_resourceextraction,
          negimage_takingjobsbusiness,
          negimage_landgrabbing,
          negimage_productquality,
          dep.var.labels.include = T,
          dep.var.labels = c("Coop With",     "Behavior of ",    "Resource",   "Taking Jobs",   "Land",     "Product"),
          column.labels   = c("Undem Leaders", "Chinese Citzns", "Extraction", "and Business",  "Grabbing", "Quality"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(negimage_cooperateundemocratic, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_chinesecitizenbehavior, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_resourceextraction, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_takingjobsbusiness, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_landgrabbing, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(negimage_productquality, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(negimage_cooperateundemocratic)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_chinesecitizenbehavior)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_resourceextraction)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_takingjobsbusiness)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_landgrabbing)$p.value %>% round(ROUND_NUM),
              calc_morans_i(negimage_productquality)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y","Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_06_full.tex"))

# Table 7 ----------------------------------------------------------------------
stargazer(china_dontknow_index,
          china.influence.econ.activity_DONTKNOW,
          china.econpol.influence.positive_DONTKNOW,
          china.aid.good.job.meet.country.needs_DONTKNOW,
          china.help.country_DONTKNOW,
          dep.var.labels.include = T,
          dep.var.labels = c("Chinese Q Don't", "Chinese Econ Activity",  "Econ/Pol Influ.",   "Chinese Aid Meets",     "China Helps"),
          column.labels   = c("Know [Index]",   "Influ. Economy [DK]",    "Pos. or Neg. [DK]", "Country's Needs [DK]",  "Country [DK]"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(china_dontknow_index, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.influence.econ.activity_DONTKNOW, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.econpol.influence.positive_DONTKNOW, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.aid.good.job.meet.country.needs_DONTKNOW, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(china.help.country_DONTKNOW, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(china_dontknow_index)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.influence.econ.activity_DONTKNOW)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.econpol.influence.positive_DONTKNOW)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.aid.good.job.meet.country.needs_DONTKNOW)$p.value %>% round(ROUND_NUM),
              calc_morans_i(china.help.country_DONTKNOW)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer)),
          out=file.path(tables_file_path, "table_07_full.tex"))

# ROUND 4 MODELS ===============================================================

# Table x ----------------------------------------------------------------------
stargazer(china.help.country,
          usa.help.country,
          dep.var.labels.include = T,
          dep.var.labels = c("Believes","Believes"),
          column.labels   = c("China Helps", "US Helps"),
          keep=c("completed_near_china.plNA.30km.bin",   "planned_near_china.plNA.30km.bin"),
          covariate.labels = c("China Completed", "China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned infrastructure $p$-value", 
              tryCatch(round(linearHypothesis(china.help.country, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.help.country, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(china.help.country)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.help.country)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "round4_table.tex"))

# Table x - Planned Eventually Completed ---------------------------------------
stargazer(china.help.country,
          usa.help.country,
          dep.var.labels.include = T,
          dep.var.labels = c("Believes","Believes"),
          column.labels   = c("China Helps", "US Helps"),
          keep=c("completed_near_china.plNAcmpltd.30km.bin",   "planned_near_china.plNAcmpltd.30km.bin"),
          covariate.labels = c("China Completed", "China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned infrastructure $p$-value", 
              tryCatch(round(linearHypothesis(china.help.country, "completed_near_china.plNAcmpltd.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(usa.help.country, "completed_near_china.plNAcmpltd.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(china.help.country)$p.value %>% round(ROUND_NUM),
              calc_morans_i(usa.help.country)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "round4_table_plannedCompleted.tex"))

# ROUND 2-5 MODELS =============================================================

# Table 2 - Full ---------------------------------------------------------------
stargazer(lib_dem_val_index_full,
          blvs_mult_parties_good_full,
          blvs_mult_parties_create_choice_full,
          blvs_ctzn_should_join_any_cso_full,
          blvs_democ_best_system_full,
          blvs_elec_good_full,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNA.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(lib_dem_val_index_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer, buffer)),
          out=file.path(tables_file_path, "table_02_full.tex"))

# Table 2 - Restricted ---------------------------------------------------------
stargazer(lib_dem_val_index_restricted,
          blvs_mult_parties_good_restricted,
          blvs_mult_parties_create_choice_restricted,
          blvs_ctzn_should_join_any_cso_restricted,
          blvs_democ_best_system_restricted,
          blvs_elec_good_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNA.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_02_restricted.tex"))

# Table 2 - Planned Eventually Completed: Full ---------------------------------
stargazer(lib_dem_val_index_full,
          blvs_mult_parties_good_full,
          blvs_mult_parties_create_choice_full,
          blvs_ctzn_should_join_any_cso_full,
          blvs_democ_best_system_full,
          blvs_elec_good_full,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNAcmpltd.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(lib_dem_val_index_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer, buffer)),
          out=file.path(tables_file_path, "table_02_plannedCompleted_full.tex"))

# Table 2 - Planned Eventually Completed: Restricted ---------------------------
stargazer(lib_dem_val_index_restricted,
          blvs_mult_parties_good_restricted,
          blvs_mult_parties_create_choice_restricted,
          blvs_ctzn_should_join_any_cso_restricted,
          blvs_democ_best_system_restricted,
          blvs_elec_good_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNAcmpltd.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_02_plannedCompleted_restricted.tex"))

# Table 4 ----------------------------------------------------------------------
stargazer(lib_dem_val_index,
          blvs_mult_parties_good_restricted,
          blvs_mult_parties_create_choice_restricted,
          blvs_ctzn_should_join_any_cso_restricted,
          blvs_democ_best_system_restricted,
          blvs_elec_good_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin",
                 "completed_near_ukaid.30km.bin", "planned_near_ukaid.30km.bin"),
          covariate.labels = c("USA Completed","USA Planned",
                               "UK Completed","UK Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [UK]", 
              tryCatch(round(linearHypothesis(lib_dem_val_index, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_good_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_mult_parties_create_choice_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_ctzn_should_join_any_cso_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_democ_best_system_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(blvs_elec_good_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(lib_dem_val_index)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_good_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_mult_parties_create_choice_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_ctzn_should_join_any_cso_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_democ_best_system_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(blvs_elec_good_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer)),
          out=file.path(tables_file_path, "table_04_restricted.tex"))














