# Make Tables

buffer <- 30
planned_cutoff_year <- 2010

#models <- readRDS(file.path(results_file_path, "models_30km.Rds"))

#models$china_influential_index_30_full %>% summary()

splag <- "T"
splag <- "F"

df <- readRDS(file.path(data_file_path, "afro_china_data.Rds"))

# ROUND 6 MODELS ===============================================================

models_r6_negimage  <- readRDS(file.path(results_file_path, "models_r6_30km_negimage.Rds"))
models_r6_posimage  <- readRDS(file.path(results_file_path, "models_r6_30km_posimage.Rds"))
models_r6_dk        <- readRDS(file.path(results_file_path, "models_r6_30km_dk.Rds"))

# Table 1 - 2010: Full ----------------------------------------------------------------
models_r6 <- readRDS(file.path(results_file_path, "models_r6_30km_influence.Rds"))

stargazer(models_r6$influential_index_full,
          models_r6$positive_influence_index_full,
          models_r6$china.most.influence_full,
          models_r6$usa.most.influence_full,
          models_r6$china.best.dev.model_full,
          models_r6$usa.best.dev.model_full,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$influential_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$positive_influence_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.best.dev.model_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.best.dev.model_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full.tex"))

# Table 1 - 2010: Restricted ----------------------------------------------------------
stargazer(models_r6$influential_index_restricted,
          models_r6$positive_influence_index_restricted,
          models_r6$china.most.influence_restricted,
          models_r6$usa.most.influence_restricted,
          models_r6$china.best.dev.model_restricted,
          models_r6$usa.best.dev.model_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$influential_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$positive_influence_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.best.dev.model_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.best.dev.model_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted.tex"))

# Table 1 - 2009: Full ---------------------------------------------------------
stargazer(models_r6$influential_index_full,
          models_r6$positive_influence_index_full,
          models_r6$china.most.influence_full,
          models_r6$usa.most.influence_full,
          models_r6$china.best.dev.model_full,
          models_r6$usa.best.dev.model_full,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$influential_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$positive_influence_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.best.dev.model_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.best.dev.model_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full_2008.tex"))

# Table 1 - 2009: Restricted ---------------------------------------------------------
stargazer(models_r6$influential_index_restricted,
          models_r6$positive_influence_index_restricted,
          models_r6$china.most.influence_restricted,
          models_r6$usa.most.influence_restricted,
          models_r6$china.best.dev.model_restricted,
          models_r6$usa.best.dev.model_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$influential_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$positive_influence_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.best.dev.model_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.best.dev.model_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted_2008.tex"))

# Table 1 - 2008: Full ---------------------------------------------------------
stargazer(models_r6$influential_index_full,
          models_r6$positive_influence_index_full,
          models_r6$china.most.influence_full,
          models_r6$usa.most.influence_full,
          models_r6$china.best.dev.model_full,
          models_r6$usa.best.dev.model_full,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_full, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$influential_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$positive_influence_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.best.dev.model_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.best.dev.model_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_full_2008.tex"))

# Table 1 - 2008: Restricted ---------------------------------------------------------
stargazer(models_r6$influential_index_restricted,
          models_r6$positive_influence_index_restricted,
          models_r6$china.most.influence_restricted,
          models_r6$usa.most.influence_restricted,
          models_r6$china.best.dev.model_restricted,
          models_r6$usa.best.dev.model_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("China Influential ","China Positive", "China Most","US Most","China Best","US Best"),
          column.labels   = c("[Index]", "[Index]", "Influence", "Influence",  "Model", "Model"),
          keep=c("completed_near_china.pl08.30km.bin", "planned_near_china.pl08.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_restricted, "completed_near_china.pl08.30km.bin = planned_near_china.pl08.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(models_r6$influential_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$positive_influence_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$usa.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$influential_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$positive_influence_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.best.dev.model_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$usa.best.dev.model_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer,buffer,buffer)),
          out=file.path(tables_file_path, "table_01_restricted_2008.tex"))


# Table 3 - Full -------------------------------------------------------------------
stargazer(models_r6$formcolnpower.most.influence_full,
          models_r6$formcolnpower.best.dev.model_full,
          dep.var.labels.include = T,
          dep.var.labels = c("Former Colonial Power", "Former Colonial Power"),
          column.labels   = c("Most Influential", "Best Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r6$formcolnpower.most.influence_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$formcolnpower.best.dev.model_full, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$formcolnpower.most.influence_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$formcolnpower.best.dev.model_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "table_03_full.tex"))

# Table 3 - Restricted -------------------------------------------------------------
stargazer(models_r6$formcolnpower.most.influence_restricted,
          models_r6$formcolnpower.best.dev.model_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("Former Colonial Power", "Former Colonial Power"),
          column.labels   = c("Most Influential", "Best Model"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(models_r6$formcolnpower.most.influence_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$formcolnpower.best.dev.model_restricted, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(models_r6$formcolnpower.most.influence_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$formcolnpower.best.dev.model_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$formcolnpower.most.influence_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$formcolnpower.best.dev.model_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "table_03_restricted.tex"))

# Table 5 ----------------------------------------------------------------------
stargazer(models_r6$posimage_chinesepeople,
          models_r6$posimage_businessinvetment,
          models_r6$posimage_infordevinvetment,
          models_r6$posimage_noninterference,
          models_r6$posimage_supportinintlaffiars,
          models_r6$posimage_productcost,
          dep.var.labels.include = T,
          dep.var.labels = c("Chinese People ","Business","Inf / Development","Non-Interference","Support in","Cost of"),
          column.labels   = c("and Culture", "Investment", "Investment",      "Policy",           "Intl Affairs", "Chinese Products"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r6$posimage_chinesepeople, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$posimage_businessinvetment, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$posimage_infordevinvetment, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$posimage_noninterference, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$posimage_supportinintlaffiars, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$posimage_productcost, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$posimage_chinesepeople)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$posimage_businessinvetment)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$posimage_infordevinvetment)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$posimage_noninterference)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$posimage_supportinintlaffiars)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$posimage_productcost)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y","Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_05_full.tex"))

# Table 6 ----------------------------------------------------------------------
stargazer(models_r6$negimage_cooperateundemocratic,
          models_r6$negimage_chinesecitizenbehavior,
          models_r6$negimage_resourceextraction,
          models_r6$negimage_takingjobsbusiness,
          models_r6$negimage_landgrabbing,
          models_r6$negimage_productquality,
          dep.var.labels.include = T,
          dep.var.labels = c("Coop With",     "Behavior of ",    "Resource",   "Taking Jobs",   "Land",     "Product"),
          column.labels   = c("Undem Leaders", "Chinese Citzns", "Extraction", "and Business",  "Grabbing", "Quality"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r6$negimage_cooperateundemocratic, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$negimage_chinesecitizenbehavior, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$negimage_resourceextraction, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$negimage_takingjobsbusiness, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$negimage_landgrabbing, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$negimage_productquality, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$negimage_cooperateundemocratic)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$negimage_chinesecitizenbehavior)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$negimage_resourceextraction)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$negimage_takingjobsbusiness)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$negimage_landgrabbing)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$negimage_productquality)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y","Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_06_full.tex"))

# Table 7 ----------------------------------------------------------------------
stargazer(models_r6$china_dontknow_index,
          models_r6$china.influence.econ.activity_DONTKNOW,
          models_r6$china.econpol.influence.positive_DONTKNOW,
          models_r6$china.aid.good.job.meet.country.needs_DONTKNOW,
          models_r6$china.help.country_DONTKNOW,
          dep.var.labels.include = T,
          dep.var.labels = c("Chinese Q Don't", "Chinese Econ Activity",  "Econ/Pol Influ.",   "Chinese Aid Meets",     "China Helps"),
          column.labels   = c("Know [Index]",   "Influ. Economy [DK]",    "Pos. or Neg. [DK]", "Country's Needs [DK]",  "Country [DK]"),
          keep=c("completed_near_china.pl10.30km.bin", "planned_near_china.pl10.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r6$china_dontknow_index, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.influence.econ.activity_DONTKNOW, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.econpol.influence.positive_DONTKNOW, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.aid.good.job.meet.country.needs_DONTKNOW, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r6$china.help.country_DONTKNOW, "completed_near_china.pl10.30km.bin = planned_near_china.pl10.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r6$china_dontknow_index)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.influence.econ.activity_DONTKNOW)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.econpol.influence.positive_DONTKNOW)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.aid.good.job.meet.country.needs_DONTKNOW)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r6$china.help.country_DONTKNOW)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer)),
          out=file.path(tables_file_path, "table_07_full.tex"))

# ROUND 4 MODELS ===============================================================

models_r4 <- readRDS(file.path(results_file_path, "models_r4_30km.Rds"))

# Table x ----------------------------------------------------------------------
stargazer(models_r4$china.help.country,
          models_r4$usa.help.country,
          dep.var.labels.include = T,
          dep.var.labels = c("Believes","Believes"),
          column.labels   = c("China Helps", "US Helps"),
          keep=c("completed_near_china.plNA.30km.bin",   "planned_near_china.plNA.30km.bin"),
          covariate.labels = c("China Completed", "China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned infrastructure $p$-value", 
              tryCatch(round(linearHypothesis(models_r4$china.help.country, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r4$usa.help.country, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r4$china.help.country)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r4$usa.help.country)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "round4_table.tex"))

# Table x - Planned Eventually Completed ---------------------------------------
stargazer(models_r4$china.help.country,
          models_r4$usa.help.country,
          dep.var.labels.include = T,
          dep.var.labels = c("Believes","Believes"),
          column.labels   = c("China Helps", "US Helps"),
          keep=c("completed_near_china.plNAcmpltd.30km.bin",   "planned_near_china.plNAcmpltd.30km.bin"),
          covariate.labels = c("China Completed", "China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned infrastructure $p$-value", 
              tryCatch(round(linearHypothesis(models_r4$china.help.country, "completed_near_china.plNAcmpltd.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r4$usa.help.country, "completed_near_china.plNAcmpltd.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r4$china.help.country)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r4$usa.help.country)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag),
            c("Country Fixed Effects", "Y", "Y"),
            c("Buffer",buffer,buffer)),
          out=file.path(tables_file_path, "round4_table_plannedCompleted.tex"))

# ROUND 2-5 MODELS =============================================================

models_r2_5 <- readRDS(file.path(results_file_path, "models_r2_5_30km.Rds"))

# Table 2 - Full ---------------------------------------------------------------
stargazer(models_r2_5$lib_dem_val_index_full,
          models_r2_5$blvs_mult_parties_good_full,
          models_r2_5$blvs_mult_parties_create_choice_full,
          models_r2_5$blvs_ctzn_should_join_any_cso_full,
          models_r2_5$blvs_democ_best_system_full,
          models_r2_5$blvs_elec_good_full,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNA.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r2_5$lib_dem_val_index_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_good_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_create_choice_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_ctzn_should_join_any_cso_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_democ_best_system_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_elec_good_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r2_5$lib_dem_val_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_good_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_create_choice_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_ctzn_should_join_any_cso_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_democ_best_system_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_elec_good_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer, buffer)),
          out=file.path(tables_file_path, "table_02_full.tex"))

# Table 2 - Restricted ---------------------------------------------------------
stargazer(models_r2_5$lib_dem_val_index_restricted,
          models_r2_5$blvs_mult_parties_good_restricted,
          models_r2_5$blvs_mult_parties_create_choice_restricted,
          models_r2_5$blvs_ctzn_should_join_any_cso_restricted,
          models_r2_5$blvs_democ_best_system_restricted,
          models_r2_5$blvs_elec_good_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNA.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(models_r2_5$lib_dem_val_index_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_good_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_create_choice_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_ctzn_should_join_any_cso_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_democ_best_system_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_elec_good_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNA.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(models_r2_5$lib_dem_val_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_create_choice_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_ctzn_should_join_any_cso_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_democ_best_system_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_elec_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r2_5$lib_dem_val_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_good_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_create_choice_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_ctzn_should_join_any_cso_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_democ_best_system_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_elec_good_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_02_restricted.tex"))

# Table 2 - Planned Eventually Completed: Full ---------------------------------
stargazer(models_r2_5$lib_dem_val_index_full,
          models_r2_5$blvs_mult_parties_good_full,
          models_r2_5$blvs_mult_parties_create_choice_full,
          models_r2_5$blvs_ctzn_should_join_any_cso_full,
          models_r2_5$blvs_democ_best_system_full,
          models_r2_5$blvs_elec_good_full,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNAcmpltd.30km.bin"),
          covariate.labels = c("China Completed","China Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value", 
              tryCatch(round(linearHypothesis(models_r2_5$lib_dem_val_index_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_good_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_create_choice_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_ctzn_should_join_any_cso_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_democ_best_system_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_elec_good_full, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r2_5$lib_dem_val_index_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_good_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_create_choice_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_ctzn_should_join_any_cso_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_democ_best_system_full)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_elec_good_full)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer, buffer)),
          out=file.path(tables_file_path, "table_02_plannedCompleted_full.tex"))

# Table 2 - Planned Eventually Completed: Restricted ---------------------------
stargazer(models_r2_5$lib_dem_val_index_restricted,
          models_r2_5$blvs_mult_parties_good_restricted,
          models_r2_5$blvs_mult_parties_create_choice_restricted,
          models_r2_5$blvs_ctzn_should_join_any_cso_restricted,
          models_r2_5$blvs_democ_best_system_restricted,
          models_r2_5$blvs_elec_good_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_china.plNA.30km.bin", "planned_near_china.plNAcmpltd.30km.bin",
                 "completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin"),
          covariate.labels = c("China Completed","China Planned",
                               "USA Completed","USA Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [China]", 
              tryCatch(round(linearHypothesis(models_r2_5$lib_dem_val_index_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_good_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_create_choice_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_ctzn_should_join_any_cso_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_democ_best_system_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_elec_good_restricted, "completed_near_china.plNA.30km.bin = planned_near_china.plNAcmpltd.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(models_r2_5$lib_dem_val_index_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_create_choice_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_ctzn_should_join_any_cso_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_democ_best_system_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_elec_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r2_5$lib_dem_val_index_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_good_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_create_choice_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_ctzn_should_join_any_cso_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_democ_best_system_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_elec_good_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y", "Y","Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer,buffer)),
          out=file.path(tables_file_path, "table_02_plannedCompleted_restricted.tex"))

# Table 4 ----------------------------------------------------------------------
stargazer(models_r2_5$lib_dem_val_index,
          models_r2_5$blvs_mult_parties_good_restricted,
          models_r2_5$blvs_mult_parties_create_choice_restricted,
          models_r2_5$blvs_ctzn_should_join_any_cso_restricted,
          models_r2_5$blvs_democ_best_system_restricted,
          models_r2_5$blvs_elec_good_restricted,
          dep.var.labels.include = T,
          dep.var.labels = c("Liberal Democratic", "Multiple Pol.", "Multiple Pol.",          "Can Join","Democracy", "Elections"),
          column.labels   = c("Values Index", "Parties Good", "Parties Create Choice",  "Any CSO", "Best System", "Good"),
          keep=c("completed_near_usaid.30km.bin", "planned_near_usaid.30km.bin",
                 "completed_near_ukaid.30km.bin", "planned_near_ukaid.30km.bin"),
          covariate.labels = c("USA Completed","USA Planned",
                               "UK Completed","UK Planned"),
          dep.var.caption = "",
          omit.stat = c("f","ser"), 
          align=TRUE,
          no.space=TRUE,
          float=FALSE,
          column.sep.width = "8pt",
          report="vcs*",
          digits = 2,
          add.lines = list(
            c("Completed vs. planned $p$-value [US]", 
              tryCatch(round(linearHypothesis(models_r2_5$lib_dem_val_index, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_create_choice_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_ctzn_should_join_any_cso_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_democ_best_system_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_elec_good_restricted, "completed_near_usaid.30km.bin = planned_near_usaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Completed vs. planned $p$-value [UK]", 
              tryCatch(round(linearHypothesis(models_r2_5$lib_dem_val_index, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_good_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_mult_parties_create_choice_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_ctzn_should_join_any_cso_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_democ_best_system_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")),
              tryCatch(round(linearHypothesis(models_r2_5$blvs_elec_good_restricted, "completed_near_ukaid.30km.bin = planned_near_ukaid.30km.bin")[2,4],3), error = function(e) print("NA")) ),
            c("Planned Year Cut Off",planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year,planned_cutoff_year),
            c("Morans I P-Value",
              calc_morans_i(models_r2_5$lib_dem_val_index)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_good_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_mult_parties_create_choice_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_ctzn_should_join_any_cso_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_democ_best_system_restricted)$p.value %>% round(ROUND_NUM),
              calc_morans_i(models_r2_5$blvs_elec_good_restricted)$p.value %>% round(ROUND_NUM)
            ),
            c("Spatial Lag of Dep Var Included", splag, splag, splag, splag, splag, splag),
            c("Country Fixed Effects", "Y", "Y", "Y","Y", "Y", "Y"),
            c("Buffer",buffer,buffer,buffer,buffer, buffer)),
          out=file.path(tables_file_path, "table_04_restricted.tex"))














